name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: linux
            runs-on: ubuntu-24.04

          - os: macos
            runs-on: macos-15

    name: ${{ matrix.os }}
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Install GFortran (macOS)
        if: matrix.os == 'macos'
        run: |
          brew install gcc@15
          FC_PATH="$(command -v gfortran-15)"
          echo "FC=$FC_PATH" >> "$GITHUB_ENV"

      - name: Verify all exercises
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .
          ctest -V
