name: cmake

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  check-up-to-date:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Check if all exercise cmake files are up to date
        run: ./bin/check-cmake-files-up-to-date
